services:
  mariadb:
    image: mariadb:10.11
    container_name: kalendar-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kalendar
      MYSQL_USER: kalendar_user
      MYSQL_PASSWORD: kalendar_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    container_name: dashboard-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/kalendar?useUnicode=true&characterEncoding=utf8mb4&tinyInt1isBit=false
      - SPRING_DATASOURCE_USERNAME=kalendar_user
      - SPRING_DATASOURCE_PASSWORD=kalendar_password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mariadb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    restart: always
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus_data:/prometheus
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mariadb_data:
  prometheus_data:
  grafana_data:
